-- MySQL Script generated by MySQL Workbench
-- Wed Sep  7 15:27:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd-20171051
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd-20171051` ;

-- -----------------------------------------------------
-- Schema bd-20171051
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-20171051` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd-20171051` ;

-- -----------------------------------------------------
-- Table `bd-20171051`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`insumo` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`insumo` (
  `id_insumo` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `unidad` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_insumo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`tipo_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`tipo_actividad` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`tipo_actividad` (
  `id_tipo_actividad` BIGINT NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `duracion_estimada_dias` INT NULL DEFAULT NULL,
  `frecuencia_dias` INT NULL DEFAULT NULL,
  `tiempo_max_cultivo` INT NULL DEFAULT NULL,
  `tiempo_min_cultivo` INT NULL DEFAULT NULL,
  `id_insumo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_actividad`),
  INDEX `FKl5gioeoa7lildeaupcx954aew` (`id_insumo` ASC) VISIBLE,
  CONSTRAINT `FKl5gioeoa7lildeaupcx954aew`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `bd-20171051`.`insumo` (`id_insumo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`lote` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`lote` (
  `id_lote` BIGINT NOT NULL AUTO_INCREMENT,
  `area_ha` INT NULL DEFAULT NULL,
  `ubicacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lote`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`tipo_siembra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`tipo_siembra` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`tipo_siembra` (
  `id_tipo_siembra` BIGINT NOT NULL AUTO_INCREMENT,
  `areax_planta` DOUBLE NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `plantasx_ha` INT NULL DEFAULT NULL,
  `tipo_surco` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_siembra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`siembra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`siembra` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`siembra` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha_fin` DATETIME(6) NULL DEFAULT NULL,
  `fecha_inicio` DATETIME(6) NULL DEFAULT NULL,
  `hijuelos_sembrados` INT NULL DEFAULT NULL,
  `id_lote` BIGINT NULL DEFAULT NULL,
  `id_tipo_siembra` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7895npx6jsx7dkgpovaer26d1` (`id_lote` ASC) VISIBLE,
  INDEX `FKr39m0iy9f54qf4xggble8u08w` (`id_tipo_siembra` ASC) VISIBLE,
  CONSTRAINT `FK7895npx6jsx7dkgpovaer26d1`
    FOREIGN KEY (`id_lote`)
    REFERENCES `bd-20171051`.`lote` (`id_lote`),
  CONSTRAINT `FKr39m0iy9f54qf4xggble8u08w`
    FOREIGN KEY (`id_tipo_siembra`)
    REFERENCES `bd-20171051`.`tipo_siembra` (`id_tipo_siembra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`actividad` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`actividad` (
  `id_actividad` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad_insumo` DOUBLE NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_fin` DATETIME(6) NULL DEFAULT NULL,
  `fecha_inicio` DATETIME(6) NULL DEFAULT NULL,
  `id_insumo` BIGINT NULL DEFAULT NULL,
  `id_siembra` BIGINT NULL DEFAULT NULL,
  `id_tipo_actividad` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_actividad`),
  INDEX `FKsmx1cttb9o7dc4sqxmpn8nuvi` (`id_insumo` ASC) VISIBLE,
  INDEX `FK85qvtwwh4sp7113e5rv4eyq24` (`id_siembra` ASC) VISIBLE,
  INDEX `FK3poo1sqltrp800vhevt1n5ylr` (`id_tipo_actividad` ASC) VISIBLE,
  CONSTRAINT `FK3poo1sqltrp800vhevt1n5ylr`
    FOREIGN KEY (`id_tipo_actividad`)
    REFERENCES `bd-20171051`.`tipo_actividad` (`id_tipo_actividad`),
  CONSTRAINT `FK85qvtwwh4sp7113e5rv4eyq24`
    FOREIGN KEY (`id_siembra`)
    REFERENCES `bd-20171051`.`siembra` (`id`),
  CONSTRAINT `FKsmx1cttb9o7dc4sqxmpn8nuvi`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `bd-20171051`.`insumo` (`id_insumo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `rol` CHAR(1) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `telefono_fijo` VARCHAR(255) NULL DEFAULT NULL,
  `telefono_movil` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`agricultor_lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`agricultor_lote` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`agricultor_lote` (
  `id_agricultor_lote` BIGINT NOT NULL AUTO_INCREMENT,
  `rol` CHAR(1) NULL DEFAULT NULL,
  `id_lote` BIGINT NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_agricultor_lote`),
  INDEX `FK26iuorrdfii99n0p6ciin02su` (`id_lote` ASC) VISIBLE,
  INDEX `FKqio70sym9cfi9ctm3y0rryvks` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK26iuorrdfii99n0p6ciin02su`
    FOREIGN KEY (`id_lote`)
    REFERENCES `bd-20171051`.`lote` (`id_lote`),
  CONSTRAINT `FKqio70sym9cfi9ctm3y0rryvks`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd-20171051`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`cliente_agricultor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`cliente_agricultor` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`cliente_agricultor` (
  `id_cliente_agricultor` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATETIME(6) NULL DEFAULT NULL,
  `id_agricultor` BIGINT NULL DEFAULT NULL,
  `id_cliente` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente_agricultor`),
  INDEX `FKcas5g579o7wswg8w967uwdyo3` (`id_agricultor` ASC) VISIBLE,
  INDEX `FKnd2ro0ieot1xg4194lwftbm87` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `FKcas5g579o7wswg8w967uwdyo3`
    FOREIGN KEY (`id_agricultor`)
    REFERENCES `bd-20171051`.`usuario` (`id_usuario`),
  CONSTRAINT `FKnd2ro0ieot1xg4194lwftbm87`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `bd-20171051`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`configuracion_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`configuracion_pedidos` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`configuracion_pedidos` (
  `id_configuracion_pedidos` BIGINT NOT NULL AUTO_INCREMENT,
  `dias_limite_pago` INT NULL DEFAULT NULL,
  `fecha_inicio` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_configuracion_pedidos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`cosecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`cosecha` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`cosecha` (
  `id_cosecha` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad_obtenida` INT NULL DEFAULT NULL,
  `fecha_fin` DATETIME(6) NULL DEFAULT NULL,
  `fecha_inicio` DATETIME(6) NULL DEFAULT NULL,
  `id_siembra` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cosecha`),
  INDEX `FKsn4nbc3arfrjjew7rfvi0th44` (`id_siembra` ASC) VISIBLE,
  CONSTRAINT `FKsn4nbc3arfrjjew7rfvi0th44`
    FOREIGN KEY (`id_siembra`)
    REFERENCES `bd-20171051`.`siembra` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`costo_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`costo_insumo` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`costo_insumo` (
  `id_costo_insumo` BIGINT NOT NULL AUTO_INCREMENT,
  `costo` DOUBLE NULL DEFAULT NULL,
  `fecha_inicio` DATETIME(6) NULL DEFAULT NULL,
  `id_insumo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_costo_insumo`),
  INDEX `FKpb1o4v48c3t678wuqxs22dshu` (`id_insumo` ASC) VISIBLE,
  CONSTRAINT `FKpb1o4v48c3t678wuqxs22dshu`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `bd-20171051`.`insumo` (`id_insumo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`variedad_platano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`variedad_platano` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`variedad_platano` (
  `id_variedad` BIGINT NOT NULL AUTO_INCREMENT,
  `dias_cosecha` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_variedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd-20171051`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd-20171051`.`pedido` ;

CREATE TABLE IF NOT EXISTS `bd-20171051`.`pedido` (
  `id_pedido` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_entrega` DATETIME(6) NULL DEFAULT NULL,
  `fecha_pedido` DATETIME(6) NULL DEFAULT NULL,
  `mercado` BIT(1) NULL DEFAULT NULL,
  `pago_aceptado` BIT(1) NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `verificacion_pago` VARCHAR(255) NULL DEFAULT NULL,
  `id_cliente_agricultor` BIGINT NULL DEFAULT NULL,
  `id_configuracion_pedidos` BIGINT NULL DEFAULT NULL,
  `id_variedad_platano` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `FK6c6695toi9um0ld54yq8dldf4` (`id_cliente_agricultor` ASC) VISIBLE,
  INDEX `FKntyn13gmclxosp7c5si9jx1gn` (`id_configuracion_pedidos` ASC) VISIBLE,
  INDEX `FKt7xc6ap9gpqmuaj1devk60oip` (`id_variedad_platano` ASC) VISIBLE,
  CONSTRAINT `FK6c6695toi9um0ld54yq8dldf4`
    FOREIGN KEY (`id_cliente_agricultor`)
    REFERENCES `bd-20171051`.`cliente_agricultor` (`id_cliente_agricultor`),
  CONSTRAINT `FKntyn13gmclxosp7c5si9jx1gn`
    FOREIGN KEY (`id_configuracion_pedidos`)
    REFERENCES `bd-20171051`.`configuracion_pedidos` (`id_configuracion_pedidos`),
  CONSTRAINT `FKt7xc6ap9gpqmuaj1devk60oip`
    FOREIGN KEY (`id_variedad_platano`)
    REFERENCES `bd-20171051`.`variedad_platano` (`id_variedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
